tactic_dict = {"enterprise":'"Reconnaissance", "Resource Development", "Initial Access", "Execution", "Persistence", "Privilege Escalation", "Defense Evasion", "Credential Access", "Discovery", "Lateral Movement", "Collection", "Command and Control", "Exfiltration", and "Impact"',\
                "mobile":'"Initial Access", "Execution", "Persistence", "Privilege Escalation", "Defense Evasion", "Credential Access", "Discovery", "Lateral Movement", "Collection", "Command and Control", "Exfiltration", and "Impact"',\
                "industrial control system":'"Initial Access", "Execution", "Persistence", "Privilege Escalation", "Evasion", "Discovery", "Lateral Movement", "Collection", "Command and Control", "Inhibit Response Function", "Impair Process Control" and "Impact"'}

tactic_dict_list = {"enterprise":["Reconnaissance", "Resource Development", "Initial Access", "Execution", "Persistence", "Privilege Escalation", "Defense Evasion", "Credential Access", "Discovery", "Lateral Movement", "Collection", "Command and Control", "Exfiltration", "Impact"],\
                    "mobile":["Initial Access", "Execution", "Persistence", "Privilege Escalation", "Defense Evasion", "Credential Access", "Discovery", "Lateral Movement", "Collection", "Command and Control", "Exfiltration", "Impact"],\
                    "industrial control system":["Initial Access", "Execution", "Persistence", "Privilege Escalation", "Evasion", "Discovery", "Lateral Movement", "Collection", "Command and Control", "Inhibit Response Function", "Impair Process Control", "Impact"]}

all_enterprise = """\
Techniques of "Reconnaissance" include "Active Scanning", "Gather Victim Host Information", "Gather Victim Identity Information", "Gather Victim Network Information", "Gather Victim Org Information", "Phishing for Information", "Search Closed Sources", "Search Open Technical Databases", "Search Open Websites/Domains", and "Search Victim-Owned Websites".
Techniques of "Resource Development" include "Acquire Access", "Acquire Infrastructure", "Compromise Accounts", "Compromise Infrastructure", "Develop Capabilities", "Establish Accounts",  "Obtain Capabilities", and "Stage Capabilities".
Techniques of "Initial Access" include "Content Injection", "Drive-by Compromise", "Exploit Public-Facing Application", "External Remote Services", "Hardware Additions", "Phishing", "Replication Through Removable Media", "Supply Chain Compromise", "Trusted Relationship", and "Valid Accounts".
Techniques of "Execution" include "Cloud Administration Command", "Command and Scripting Interpreter", "Container Administration Command", "Deploy Container", "Exploitation for Client Execution", "Inter-Process Communication", "Native API", "Scheduled Task/Job", "Serverless Execution", "Shared Modules", "Software Deployment Tools", "System Services", "User Execution", and "Windows Management Instrumentation".
Techniques of "Persistence" include "Account Manipulation", "BITS Jobs", "Boot or Logon Autostart Execution", "Boot or Logon Initialization Scripts", "Browser Extensions", "Compromise Host Software Binary", "Create Account", "Create or Modify System Process", "Event Triggered Execution", "External Remote Services", "Hijack Execution Flow", "Implant Internal Image", "Modify Authentication Process", "Office Application Startup", "Power Settings", "Pre-OS Boot", "Scheduled Task/Job", "Server Software Component", "Traffic Signaling", and "Valid Accounts".
Techniques of "Privilege Escalation" include "Abuse Elevation Control Mechanism", "Access Token Manipulation", "Account Manipulation", "Boot or Logon Autostart Execution", "Boot or Logon Initialization Scripts", "Create or Modify System Process", "Domain or Tenant Policy Modification", "Escape to Host", "Event Triggered Execution", "Exploitation for Privilege Escalation", "Hijack Execution Flow", "Process Injection", "Scheduled Task/Job", and "Valid Accounts".
Techniques of "Defense Evasion" include "Abuse Elevation Control Mechanism", "AccessToken Manipulation", "BITS Jobs", "Build Image on Host", "Debugger Evasion", "Deobfuscate/Decode Files or Information", "Deploy Container", "Direct Volume Access", "Domain or Tenant Policy Modification", "Execution Guardrails", "Exploitation for Defense Evasion", "File and Directory Permissions Modification", "Hide Artifacts", "Hijack Execution Flow", "Impair Defenses", "Impersonation", "Indicator Removal", "Indirect Command Execution", "Masquerading", "Modify Authentication Process", "Modify Cloud Compute Infrastructure", "Modify Registry", "Modify System Image", "Network Boundary Bridging", "Obfuscated Files or Information", "Plist File Modification", "Pre-OS Boot", "Process Injection", "Reflective Code Loading", "Rogue Domain Controller", "Rootkit", "Subvert Trust Controls", "System Binary Proxy Execution", "System Script Proxy Execution", "Template Injection", "Traffic Signaling", "Trusted Developer Utilities Proxy Execution", "Unused/Unsupported Cloud Regions", "Use Alternate Authentication Material", "Valid Accounts", "Virtualization/Sandbox Evasion", "Weaken Encryption", and "XSL Script Processing".
Techniques of "Credential Access" include "Adversary-in-the-Middle", "Brute Force", "Credentials from Password Stores", "Exploitation for Credential Access", "Forced Authentication", "Forge Web Credentials", "Input Capture", "Modify Authentication Process", "Multi-Factor Authentication Interception", "Multi-Factor Authentication Request Generation", "Network Sniffing", "OS Credential Dumping", "Steal Application Access Token", "Steal or Forge Authentication Certificates", "Steal or Forge Kerberos Tickets", "Steal Web Session Cookie", and "Unsecured Credentials".
Techniques of "Discovery" include "Account Discovery", "Application Window Discovery", "Browser Information Discovery", "Cloud Infrastructure Discovery", "Cloud Service Dashboard", "Cloud Service Discovery", "Cloud Storage Object Discovery", "Container and Resource Discovery", "Debugger Evasion", "Device Driver Discovery", "Domain Trust Discovery", "File and Directory Discovery", "Group Policy Discovery", "Log Enumeration", "Network Service Discovery", "Network Share Discovery", "Network Sniffing", "Password Policy Discovery", "Peripheral Device Discovery", "Permission Groups Discovery", "Process Discovery", "Query Registry", "Remote System Discovery", "Software Discovery", "System Information Discovery", "System Location Discovery", "System Network Configuration Discovery", "System Network Connections Discovery", "System Owner/User Discovery", "System Service Discovery", "System Time Discovery", "Virtualization/Sandbox Evasion".
Techniques of "Lateral Movement" include "Exploitation of Remote Services", "Internal Spearphishing", "Lateral Tool Transfer", "Remote Service Session Hijacking", "Remote Services", "Replication Through Removable Media", "Software Deployment Tools", "Taint Shared Content", and "Use Alternate Authentication Material".
Techniques of "Collection" include "Adversary-in-the-Middle", "Archive Collected Data", "Audio Capture", "Automated Collection", "Browser Session Hijacking", "Clipboard Data", "Data from Cloud Storage", "Data from Configuration Repository", "Data from Information Repositories", "Data from Local System", "Data from Network Shared Drive", "Data from Removable Media", "Data Staged", "Email Collection", "Input Capture", "Screen Capture", "Video Capture".
Techniques of "Command and Control" include "Application Layer Protocol", "Communication Through Removable Media", "Content Injection", "Data Encoding", "Data Obfuscation", "Dynamic Resolution", "Encrypted Channel", "Fallback Channels", "Hide Infrastructure", "Ingress Tool Transfer", "Multi-Stage Channels", "Non-Application Layer Protocol", "Non-Standard Port", "Protocol Tunneling", "Proxy", "Remote Access Software", "Traffic Signaling", and "Web Service".
Techniques of "Exfiltration" include "Automated Exfiltration", "Data Transfer Size Limits", "Exfiltration Over Alternative Protocol", "Exfiltration Over C2 Channel", "Exfiltration Over Other Network Medium", "Exfiltration Over Physical Medium", "Exfiltration Over Web Service", "Scheduled Transfer", and "Transfer Data to Cloud Account".
Techniques of "Impact" include "Account Access Removal", "Data Destruction", "Data Encrypted for Impact", "Data Manipulation", "Defacement", "Disk Wipe", "Endpoint Denial of Service", "Financial Theft", "Firmware Corruption", "Inhibit System Recovery", "Network Denial of Service", "Resource Hijacking", "Service Stop", and "System Shutdown/Reboot".
"""

all_mobile = """\
Techniques of "Initial Access" include "Replication Through Removable Media", "Lockscreen Bypass", "Application Versioning", "Exploitation for Initial Access", "Supply Chain Compromise", "Drive-By Compromise", and "Phishing".
Techniques of "Execution" include "Exploitation for Client Execution", "Scheduled Task/Job", "Native API", and "Command and Scripting Interpreter".
Techniques of "Persistence" include "Foreground Persistence", "Event Triggered Execution", "Compromise Application Executable", "Scheduled Task/Job", "Boot or Logon Initialization Scripts", "Compromise Client Software Binary", and "Hijack Execution Flow".
Techniques of "Privilege Escalation" include "Abuse Elevation Control Mechanism", "Process Injection", and "Exploitation for Privilege Escalation".
Techniques of "Defense Evasion" include "Execution Guardrails", "Obfuscated Files or Information", "Foreground Persistence", "Process Injection", "Application Versioning", "Masquerading", "Proxy Through Victim", "Input Injection", "Native API", "Hide Artifacts", "Indicator Removal on Host", "Virtualization/Sandbox Evasion", "Impair Defenses", "Hooking", "Download New Code at Runtime", and "Subvert Trust Controls".
Techniques of "Credential Access" include "Credentials from Password Store", "Input Capture", "Steal Application Access Token", "Clipboard Data", and "Access Notifications".
Techniques of "Discovery" include "File and Directory Discovery", "Process Discovery", "System Information Discovery", "System Network Connections Discovery", "Location Tracking", "Software Discovery", "System Network Configuration Discovery", and "Network Service Scanning".
Techniques of "Lateral Movement" include "Replication Through Removable Media", and "Exploitation of Remote Services".
Techniques of "Collection" include "Protected User Data", "Screen Capture", "Adversary-in-the-Middle", "Location Tracking", "Input Capture", "Stored Application Data", "Call Control", "Archive Collected Data", "Audio Capture", "Data from Local System", "Video Capture", "Clipboard Data", and "Access Notifications".
Techniques of "Command and Control" include "Application Layer Protocol", "Encrypted Channel", "Non-Standard Port", "Out of Band Data", "Web Service", "Ingress Tool Transfer", "Dynamic Resolution", "Call Control", and "Remote Access Software".
Techniques of "Exfiltration" include "Exfiltration Over Alternative Protocol", and "Exfiltration Over C2 Channel".
Techniques of "Impact" include "Account Access Removal", "Endpoint Denial of Service", "Data Encrypted for Impact", "Generate Traffic from Victim", "Call Control", "SMS Control", "Input Injection", "Data Manipulation", "Data Destruction", and "Network Denial of Service".
"""

all_ICS = """\
Techniques of "Initial Access" include "Drive-by Compromise", "Remote Services", "External Remote Services", "Spearphishing Attachment", "Transient Cyber Asset", "Replication Through Removable Media", "Supply Chain Compromise", "Internet Accessible Device", "Wireless Compromise", "Rogue Master", "Exploit Public-Facing Application", and "Exploitation of Remote Services".
Techniques of "Execution" include "Graphical User Interface", "Native API", "Execution through API", "Hooking", "Autorun Image", "Change Operating Mode", "Scripting", "Command-Line Interface", "Modify Controller Tasking", and "User Execution".
Techniques of "Persistence" include "Valid Accounts", "Project File Infection", "System Firmware", "Modify Program", "Hardcoded Credentials", and "Module Firmware".
Techniques of "Privilege Escalation" include "Hooking", and "Exploitation for Privilege Escalation".
Techniques of "Evasion" include "Rootkit", "Spoof Reporting Message", "Change Operating Mode", "Masquerading", "Exploitation for Evasion", "System Binary Proxy Execution", and "Indicator Removal on Host".
Techniques of "Discovery" include "Wireless Sniffing", "Network Sniffing", "Network Connection Enumeration", "Remote System Discovery", and "Remote System Information Discovery".
Techniques of "Lateral Movement" include "Remote Services", "Valid Accounts", "Default Credentials", "Lateral Tool Transfer", "Hardcoded Credentials", "Program Download", and "Exploitation of Remote Services".
Techniques of "Collection" include "Screen Capture", "I/O Image", "Detect Operating Mode", "Monitor Process State", "Wireless Sniffing", "Data from Information Repositories", "Program Upload", "Automated Collection", "Adversary-in-the-Middle", "Data from Local System", and "Point & Tag Identification".
Techniques of "Command and Control" include "Standard Application Layer Protocol", "Commonly Used Port", and "Connection Proxy".
Techniques of "Inhibit Response Function" include "Block Serial COM", "Alarm Suppression", "Activate Firmware Update Mode", "Denial of Service", "Change Credential", "Rootkit", "System Firmware", "Data Destruction", "Device Restart/Shutdown", "Service Stop", "Modify Alarm Settings", "Block Command Message", "Manipulate I/O Image", and "Block Reporting Message".
Techniques of "Impair Process Control" include "Unauthorized Command Message", "Spoof Reporting Message", "Module Firmware", "Modify Parameter", and "Brute Force I/O".
Techniques of "Impact" include "Damage to Property", "Manipulation of Control", "Loss of Availability", "Manipulation of View", "Denial of Control", "Loss of View", "Denial of View", "Loss of Productivity and Revenue", "Loss of Control", "Loss of Protection", "Loss of Safety", and "Theft of Operational Information".
"""